Repository ChicoState/djsongmatch, pull requests merged in 2025-05, with the labels that each got.

#120 Adds workflows for linting and type checking
  .github/workflows/lint.yml
  .github/workflows/typecheck.yml
  frontend/lib/hooks.ts
Labels: enhancement

#113 Advanced Filters, Year Range
  frontend/@frontend/components/ui/popover.tsx
  frontend/app/_components/AdvancedFilters.tsx
  frontend/app/_components/ButtonSliderSection.tsx
  frontend/app/_components/RecommendationTable.tsx
  frontend/app/actions.ts
  frontend/components/ui/button.tsx
  frontend/lib/hooks.ts
  frontend/lib/utils.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: enhancement

#126 Adds real descriptions for slider tooltips
  frontend/app/_components/AdvancedFilters.tsx
  frontend/app/_components/ButtonSliderSection.tsx
Labels: documentation, enhancement

#114 Update pre-processing script to use rank-based quantile distribution …
  backend/api/database/seed.py
  backend/api/routes/songs.py
  backend/api/services/song_service.py
  backend/assets/Processed_ClassicHit.csv
  backend/assets/faiss_index.bin
  backend/assets/faiss_song_ids.pkl
  backend/assets/feature_stats.pkl
  backend/assets/kmeans_model.pkl
  backend/constants.py
  backend/scripts/cluster.py
  backend/scripts/manage_data.py
  backend/scripts/operations/cluster.py
  backend/scripts/operations/index.py
  backend/scripts/operations/pre_process.py
  backend/scripts/operations/seed.py
  backend/scripts/operations/update.py
  backend/scripts/pre_process_data.py
  backend/scripts/run_seed.py
Labels: enhancement

#84 Added the login and signup page using Firebase
  docker-compose.yml
  frontend/app/_components/Help.tsx
  frontend/app/_components/TopNav.tsx
  frontend/app/layout.tsx
  frontend/app/login/layout.tsx
  frontend/app/login/page.tsx
  frontend/app/signup/layout.tsx
  frontend/app/signup/page.tsx
  frontend/lib/firebaseConfig.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: enhancement

#117 Changes Sliders to Automatically Match Input Song
  frontend/app/_components/ButtonSliderSection.tsx
  frontend/app/_components/RecommendationTable.tsx
  frontend/app/_components/SearchBarSection.tsx
  frontend/lib/hooks.ts
Labels: enhancement

#129 Update ANN recommendation algorithm to improve speed
  backend/api/services/song_service.py
  backend/requirements.txt
  backend/scripts/operations/index.py
  frontend/app/login/page.tsx
  frontend/eslint.config.mjs
Labels: enhancement

#130 Polish README.md, adding project description and making instructions …
  README.md
Labels: documentation

#125 Allows user to select song from playlist as input song
  frontend/app/_components/PlaylistTable.tsx
  frontend/app/_components/SearchBarSection.tsx
  frontend/app/login/page.tsx
Labels: enhancement
