Repository ChicoState/djsongmatch, pull requests merged in 2025-04, with the labels that each got.

#73 sqlalchemy_setup, Updates frontend with new db
  .dockerignore
  .gitignore
  docker-compose.yml
  frontend/Dockerfile
  frontend/app/actions.ts
  frontend/app/api/songs/route.ts
  frontend/db.db
  frontend/db/index.ts
  frontend/db/relations.ts
  frontend/db/schema.ts
  frontend/drizzle.config.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/pnpm-lock.yaml
  frontend/pnpm-workspace.yaml
Labels: enhancement

#74 project_restructure Update Compose to Follow Project Structure
  docker-compose.yml
Labels: bug

#80 Fix config bug in run_seed.py script
  backend/scripts/run_seed.py
Labels: bug

#76 Adds in a little Help pop up
  frontend/app/_components/Help.tsx
  frontend/app/_components/TopNav.tsx
Labels: documentation, enhancement

#75 Migrates Database Source to Supabase
  frontend/app/actions.ts
  frontend/db/index.ts
  frontend/drizzle.config.ts
Labels: enhancement

#82 Tables Add/Remove/Reorder
  backend/api/__init__.py
  backend/api/routes/songs.py
  backend/api/services/song_service.py
  backend/requirements.txt
  frontend/app/_components/ButtonSliderSection.tsx
  frontend/app/_components/PlaylistTable.tsx
  frontend/app/_components/RecommendationTable.tsx
  frontend/app/_components/SearchBarSection.tsx
  frontend/app/_components/TableSection.tsx
  frontend/app/_components/TitleArtist.tsx
  frontend/app/actions.ts
  frontend/app/page.tsx
  frontend/components/ui/SongForm.tsx
  frontend/components/ui/command.tsx
  frontend/components/ui/songtable.tsx
  frontend/components/ui/table.tsx
  frontend/db/schema.ts
  frontend/lib/utils.ts
  frontend/package.json
  frontend/pnpm-lock.yaml
Labels: enhancement

#105 Confirm trash
  frontend/app/_components/Help.tsx
  frontend/app/_components/PlaylistTable.tsx
  frontend/app/_components/TrashConfirm.tsx
Labels: enhancement

#98 Auto-Scroll Playlist to Bottom When Song Gets Added, Resolves #95
  frontend/app/_components/PlaylistTable.tsx
  frontend/components/ui/table.tsx
Labels: enhancement

#112 Integrate Clustering with Frontend
  backend/api/routes/songs.py
  frontend/app/_components/ButtonSliderSection.tsx
  frontend/app/_components/RecommendationTable.tsx
  frontend/app/actions.ts
  frontend/components/ui/button.tsx
Labels: enhancement
